### ISSUE TITLE
Use websockets in client.js?

### ISSUE THREAD

**Issue by newhouse** [jayshenk/prefixy#27]
Hello Prefixy team! I saw @tiffanyhan speak last night at NodeSF and followed up with an e-mail about perhaps using websockets instead of firing off full HTTP requests with each keystroke. Tiffany asked if I'd create an issue here to discuss it further. I'll paraphrase my e-mail and her response to get things going:

### My original e-mail content:
Would you be interested in discussing going that route (websockets), or perhaps having that as an "option" for your customers? The most obvious things in the "pro" list of this change would be:
- Reduced connection overhead on your servers having to handle a new request/response for every keystroke typed by every user of every customer. Your demo website runs really fast at this, but at scale, these handshakes and connection limits will likely become more of an issue.
- At scale, this should result in quicker responses than an equivalent classic request/response pattern.
- Can still use authentication/namespacing.

Some cons:
- Introduces some more complexity on the server side than a typical request/response scenario.
- Introduces more dependencies.
- Idle connections would need to be "dealt with" in a way that doesn't bog the server down with wasteful connections, but also allows for the User to always have a quick/immediate response time. (probably a hybrid approach would suffice). There are various framework/library options out there that may work well for this concern.

### Tiffany's response:

> I think the socket idea is really interesting and would increase performance by quite a bit. Can you please open up an issue with these pros and cons on our Prefixy github repo? I'll give a heads up to my teammates, Walid and Jay, so they can look at it too.
> One concern I do have is that if we ever had to shard the dataset, I think we'd only be able to shard by tenant ID if we go with sockets. It seems that one advantage of the straightforward HTTP request setup that we have now, is that we'd be able to shard by tenant ID + prefix, since each request would be a brand new request. 
> 
> Anyway, that may be super hypothetical, but I'm only thinking about it since we are a free and open source service, and scaling horizontally is probably more feasible financially for us than scaling horizontally.

Your initial thought concern is a valid one depending on what you mean and are thinking about doing. Here's an example request from the demo site:
```
curl 'https://prefixy.herokuapp.com/completions?prefix=pre&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiJkZW1vIiwiaWF0IjoxNTE5OTQ2MDk2fQ.xLhmbrRxBwr9JqQ5F2Hr7ZUZK-yzhEsBnrAZsWw1wsw'
```

Perhaps you are thinking about routing requests differently based on the `prefix` and `token` combinations in order to accomplish your sharding? Not sure what you mean exactly, but hopefully it would either not be an issue after some diving in, or perhaps it may be a non-starter for this reason.

Anyways, great project you guys and if you think this sounds good at all and would like to discuss further, I'd be happy to. We could narrow down the requirements a bit more before I could take a stab at coding it out, of course, or whatever you want to do.

**Comment by tiffanyhan** [comment]
Oh yeah as for my concern, I think it would actually not be a problem, since if anything we would just be sharding redis/mongo. Connection requests would still go to one Node.js server.

**Comment by tiffanyhan** [comment]
Hi @newhouse, 

Sorry for the lag in response. Our team had the chance to talk about your proposal to implement websockets with Prefixy. While we think it's a really interesting idea, we decided it's best to table this idea for now. 

Since we're not currently experiencing any bottlenecks yet, it's hard to know what the most high priority things are to implement. We're also not sure if the overhead of negotiating a connection is worth it, if a user is only typing on a search field for 1-5 seconds.

That said, we really appreciate your interest in Prefixy. And of course, you're welcome to fork our repo and implement websockets for your own use case. If you do end up following through on it, we'll definitely be interested to see how it turns out!

-Tiffany

**Comment by newhouse** [comment]
@tiffanyhan I totally understand and it makes total sense. Perhaps I will fork this some day, but either way let me know if there's any way I can help, and best of luck you you all!

**Comment by tiffanyhan** [comment]
will do @newhouse , thanks again!
